// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXjwaGVxJremk2_sYP3vClX9LS_RCT8Jg',
    appId: '1:1066119822085:web:cee03d29a539e937e7956c',
    messagingSenderId: '1066119822085',
    projectId: 'crud-8e999',
    authDomain: 'crud-8e999.firebaseapp.com',
    databaseURL: 'https://crud-8e999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-8e999.appspot.com',
    measurementId: 'G-NDZ8HT1NCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU7MyVAgoYlNQzbYcOlD4I1yrWIllDjQo',
    appId: '1:1066119822085:android:2c440f174f11d1aee7956c',
    messagingSenderId: '1066119822085',
    projectId: 'crud-8e999',
    databaseURL: 'https://crud-8e999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-8e999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB56W05za9ZjZa3Z6WWUr4v9Ap0bie7Tdg',
    appId: '1:1066119822085:ios:08b66d3678f449f6e7956c',
    messagingSenderId: '1066119822085',
    projectId: 'crud-8e999',
    databaseURL: 'https://crud-8e999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-8e999.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB56W05za9ZjZa3Z6WWUr4v9Ap0bie7Tdg',
    appId: '1:1066119822085:ios:08b66d3678f449f6e7956c',
    messagingSenderId: '1066119822085',
    projectId: 'crud-8e999',
    databaseURL: 'https://crud-8e999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-8e999.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXjwaGVxJremk2_sYP3vClX9LS_RCT8Jg',
    appId: '1:1066119822085:web:96f5fd85f23e7b3ce7956c',
    messagingSenderId: '1066119822085',
    projectId: 'crud-8e999',
    authDomain: 'crud-8e999.firebaseapp.com',
    databaseURL: 'https://crud-8e999-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-8e999.appspot.com',
    measurementId: 'G-C3KT82BHRP',
  );
}
